networks:
  ticketing-network:
    driver: bridge

services:
  # ==========================================
  # 1. INFRASTRUCTURE & DATABASES
  # ==========================================
  mongo:
    image: mongo:latest
    container_name: mongo-event-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    networks:
      - ticketing-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ticket_lock_db
    networks:
      - ticketing-network

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    command: redis-server --notify-keyspace-events Ex
    networks:
      - ticketing-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ticketing-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ticketing-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    command: start-dev
    networks:
      - ticketing-network

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - ticketing-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ticketing-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - ticketing-network

  # ==========================================
  # 2. BACKEND MICROSERVICES
  # ==========================================
  discovery-service:
    build:
      context: ../discovery-service
    image: ticketing/discovery-service:latest
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - ticketing-network

  api-gateway:
    build:
      context: ../api-gateway
    image: ticketing/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8083:8083" # Host 8083 -> Container 8080
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATA_REDIS_HOST=redis-cache
    depends_on:
      - discovery-service
      - redis
    networks:
      - ticketing-network

  event-service:
    build:
      context: ../event-service
    image: ticketing/event-service:latest
    container_name: event-service
    ports:
      - "8080:8080" # Host 8080 -> Container 8081
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATA_MONGODB_URI=mongodb://root:rootpassword@mongo-event-db:27017/event_db?authSource=admin
    depends_on:
      - discovery-service
      - mongo
    networks:
      - ticketing-network

  ticketlock-service:
    build:
      context: ../ticketlock-service
    image: ticketing/ticketlock-service:latest
    container_name: ticketlock-service
    ports:
      - "8081:8081" # Host 8081 -> Container 8082
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/ticket_lock_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - discovery-service
      - redis
      - mysql
      - kafka
    networks:
      - ticketing-network

  order-service:
    build:
      context: ../order-service
    image: ticketing/order-service:latest
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/ticket_lock_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - discovery-service
      - mysql
      - kafka
    networks:
      - ticketing-network