global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8083' # api-gateway
          - 'host.docker.internal:8080' # event-service
          - 'host.docker.internal:8081' # ticket-lock-service
          - 'host.docker.internal:8082' # order-service