server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/events/**

        - id: ticket-lock-service
          uri: lb://ticket-lock-service
          predicates:
            - Path=/api/lock/**
          filters:
            - name: CircuitBreaker
              args:
                name: ticketLockCircuitBreaker
                fallbackUri: forward:/fallback/ticket-lock

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/fallback/orders

        - id: event-service-swagger
          uri: lb://event-service
          predicates:
            - Path=/aggregate/event-service/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        - id: ticket-lock-service-swagger
          uri: lb://ticket-lock-service
          predicates:
            - Path=/aggregate/ticket-lock-service/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        - id: order-service-swagger
          uri: lb://order-service
          predicates:
            - Path=/aggregate/order-service/v3/api-docs
          filters:
            - SetPath=/v3/api-docs
      server:
        webflux:
          routes:
            - id: event-service
              uri: lb://event-service
              predicates:
                - Path=/api/events/**

            - id: ticket-lock-service
              uri: lb://ticket-lock-service
              predicates:
                - Path=/api/lock/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: ticketLockCircuitBreaker
                    fallbackUri: forward:/fallback/ticket-lock

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: orderCircuitBreaker
                    fallbackUri: forward:/fallback/orders

            - id: event-service-swagger
              uri: lb://event-service
              predicates:
                - Path=/aggregate/event-service/v3/api-docs
              filters:
                - SetPath=/v3/api-docs

            - id: ticket-lock-service-swagger
              uri: lb://ticket-lock-service
              predicates:
                - Path=/aggregate/ticket-lock-service/v3/api-docs
              filters:
                - SetPath=/v3/api-docs

            - id: order-service-swagger
              uri: lb://order-service
              predicates:
                - Path=/aggregate/order-service/v3/api-docs
              filters:
                - SetPath=/v3/api-docs
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/ticketing-realm


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
resilience4j:
  circuitbreaker:
    instances:
      ticketLockCircuitBreaker:
        slidingWindowSize: 100
        minimumNumberOfCalls: 20
        failureRateThreshold: 60
        waitDurationInOpenState: 5000ms
        permittedNumberOfCallsInHalfOpenState: 10
      orderCircuitBreaker:
        slidingWindowSize: 100
        minimumNumberOfCalls: 20
        failureRateThreshold: 60
        waitDurationInOpenState: 5000ms
        permittedNumberOfCallsInHalfOpenState: 10
  timelimiter:
    instances:
      ticketLockCircuitBreaker:
        timeoutDuration: 3s
      orderCircuitBreaker:
        timeoutDuration: 3s
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Event Service
        url: /aggregate/event-service/v3/api-docs
      - name: Ticket Lock Service
        url: /aggregate/ticket-lock-service/v3/api-docs
      - name: Order Service
        url: /aggregate/order-service/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics"
  tracing:
    sampling:
      probability: 1.0 # 1.0 means sample 100% of requests (set to 0.1 in production)
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

# Custom Log Format
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"