spring.application.name=order-service
server.port=8082
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/order_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=rootpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Flyway Migration Configuration
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=false

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=order-service-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false

spring.kafka.producer.observations.enabled=true
spring.kafka.consumer.observations.enabled=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Custom Swagger UI Path
springdoc.swagger-ui.path=/swagger-ui.html
# Enables JSON docs generated at /v3/api-docs
springdoc.api-docs.path=/v3/api-docs

# Tracing and Logging Configuration
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

management.tracing.sampling.probability=1.0
management.zipkin.tracing.sender.type=URL_CONNECTION
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.endpoints.web.exposure.include=health,info,prometheus,metrics,configprops
# Kafka Observation Tracing Propagation
spring.kafka.template.observation-enabled=true
spring.kafka.listener.observation-enabled=true